In [1]:
# Load data
import pandas as pd

data = pd.read_csv("ae_trials.csv")
data.head()

,name,dataset,type,attempt,leader,input_size,hidden_layers,hidden_layers_divisor,z_layer_divisor,dropout,learning_rate,batch_size,gen_loss,disc_loss,val_loss,epochs
0,20230224014423,Task 2 (25% Noise),Adversarial AE,0,NaN,4096,2,2,16,0.25,0.00001,8,0.454284,1.044765,0.005560,57
1,20230224014528,Task 2 (25% Noise),Vanilla AE,0,2.023022e+13,4096,2,2,16,0.25,0.00001,8,NaN,NaN,0.002088,62
2,20230224014606,Task 2 (25% Noise),Adversarial AE,1,2.023022e+13,4096,2,2,16,0.25,0.00001,8,0.667929,0.719132,0.009296,10
3,20230224014651,Task 2 (25% Noise),Vanilla AE,1,2.023022e+13,4096,2,2,16,0.25,0.00001,8,NaN,NaN,0.002058,127
4,20230224014744,Task 2 (25% Noise),Adversarial AE,2,2.023022e+13,4096,2,2,16,0.25,0.00001,8,0.598004,0.798654,0.008213,9

In [2]:
data["len"] = [1 for d in data.values]

data.to_csv("ae_trials.csv")